### ISSUE TITLE
Gradio Web Server exiting on startup

### ISSUE THREAD

**Issue by tklentz** [tklentz/FastChat#4]
Version mismatch of Gradio and Fastchat?

Error Log:
2024-03-20 01:51:07 | ERROR | stderr | /usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_web_server_multi.py:113: GradioUnusedKwargWarning: You have unused kwarg parameters in Blocks, please remove them: {'head': '\n<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>\n'}
2024-03-20 01:51:07 | ERROR | stderr |   with gr.Blocks(
2024-03-20 01:51:07 | ERROR | stderr | Traceback (most recent call last):
2024-03-20 01:51:07 | ERROR | stderr |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2024-03-20 01:51:07 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-03-20 01:51:07 | ERROR | stderr |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2024-03-20 01:51:07 | ERROR | stderr |     exec(code, run_globals)
2024-03-20 01:51:07 | ERROR | stderr |   File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_web_server_multi.py", line 260, in <module>
2024-03-20 01:51:07 | ERROR | stderr |     demo = build_demo(
2024-03-20 01:51:07 | ERROR | stderr |   File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_web_server_multi.py", line 121, in build_demo
2024-03-20 01:51:07 | ERROR | stderr |     side_by_side_anony_list = build_side_by_side_ui_anony(models)
2024-03-20 01:51:07 | ERROR | stderr |   File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_block_arena_anony.py", line 783, in build_side_by_side_ui_anony
2024-03-20 01:51:07 | ERROR | stderr |     share_btn.click(share_click, states + model_selectors, [], js=share_js)
2024-03-20 01:51:07 | ERROR | stderr | TypeError: __call__() got an unexpected keyword argument 'js'
2024-03-20 01:51:12 | INFO | gradio_web_server_multi | args: Namespace(concurrency_count=10, controller_url='http://fastchat-controller:21001', elo_results_file=None, ga_id=None, gradio_auth_path=None, gradio_root_path=None, host='0.0.0.0', leaderboard_table_file=None, model_list_mode='once', moderate=False, multimodal=False, port=None, register_api_endpoint_file=None, share=False, show_terms_of_use=False)
2024-03-20 01:51:12 | INFO | gradio_web_server | All models: []
2024-03-20 01:51:12 | INFO | gradio_web_server | Visible models: []
2024-03-20 01:51:12 | INFO | gradio_web_server | All models: []
2024-03-20 01:51:12 | INFO | gradio_web_server | Visible models: []
2024-03-20 01:51:12 | ERROR | stderr | /usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_web_server_multi.py:113: GradioUnusedKwargWarning: You have unused kwarg parameters in Blocks, please remove them: {'head': '\n<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>\n'}
2024-03-20 01:51:12 | ERROR | stderr |   with gr.Blocks(
2024-03-20 01:51:12 | ERROR | stderr | Traceback (most recent call last):
2024-03-20 01:51:12 | ERROR | stderr |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2024-03-20 01:51:12 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-03-20 01:51:12 | ERROR | stderr |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2024-03-20 01:51:12 | ERROR | stderr |     exec(code, run_globals)
2024-03-20 01:51:12 | ERROR | stderr |   File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_web_server_multi.py", line 260, in <module>
2024-03-20 01:51:12 | ERROR | stderr |     demo = build_demo(
2024-03-20 01:51:12 | ERROR | stderr |   File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_web_server_multi.py", line 121, in build_demo
2024-03-20 01:51:12 | ERROR | stderr |     side_by_side_anony_list = build_side_by_side_ui_anony(models)
2024-03-20 01:51:12 | ERROR | stderr |   File "/usr/local/lib/python3.8/dist-packages/fastchat/serve/gradio_block_arena_anony.py", line 783, in build_side_by_side_ui_anony
2024-03-20 01:51:12 | ERROR | stderr |     share_btn.click(share_click, states + model_selectors, [], js=share_js)
2024-03-20 01:51:12 | ERROR | stderr | TypeError: __call__() got an unexpected keyword argument 'js'

**Comment by dweaver33** [comment]
If the reset I put in here works: https://github.com/tklentz/FastChat/commit/2da90481ca2a77b80d19e55a1a1d3a06074490b3

We can close this issue.
